version : 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
      files:
        - index.html
        - favicon.ico
        - styles/main.css
        - images/*
